name: Rust CI/CD

on:
  push:
    branches: [ "master", "feat/cicd" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    name: Build Ferrox
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable 

      - name: Build Binary
        run: cargo build --release --verbose

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ferrox-linux-binary
          path: target/release/ferrox
          if-no-files-found: error
      - name: Generate Release Tag
        id: tag
        run: echo "release_tag=v$(date +'%Y.%m.%d-%H%M')" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          name: Release ${{ steps.tag.outputs.release_tag }}
          draft: false
          prerelease: false
          files: |
            target/release/ferrox