name: Ferrox CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    name: Test & Build Ferrox
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable 

      - name: Run tests
        run: cargo test

      - name: Build Binary
        run: cargo build --release --verbose

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ferrox-linux-binary
          path: target/release/ferrox
          if-no-files-found: error
      - name: Get version from Cargo.toml
        id: cargo_version
        run: |
          VERSION=$(grep '^version' Cargo.toml | head -1 | cut -d '"' -f2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v. ${{ steps.cargo_version.outputs.version }}
          name: v. ${{ steps.cargo_version.outputs.version }}
          draft: false
          prerelease: false
          files: |
            target/release/ferrox